blank_issues_enabled: false

contact_links:
  - name: GitHub Discussions
    url: https://github.com/ethanKletschke/CobCash/discussions
    about: Ask questions or discuss ideas here instead of opening an issue
  - name: Documentation
    url: https://github.com/ethanKletschke/CobCash/blob/main/README.md
    about: Read the README thoroughly before opening an issue
  - name: Support Document
    url: https://github.com/ethanKletschke/CobCash/tree/main/.github/SUPPORT.md
    about: Read the SUPPORT document clearly before opening an issue
