name: Compile and Link

# Controls when the workflow will run
on: [workflow_dispatch, pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up GnuCOBOL
        uses: fabasoad/setup-cobol-action@v1.6.1
        with:
          version: 3.2

      - name: Syntax check
        run: cobc -fsyntax-only -Wfatal-errors -I src src/*.cbl

      - name: Compile (warnings)
        run: cobc -Wall -Wextra -I src -c src/*.cbl

      - name: Link executable  
        run: cobc -x -I src src/*.cbl
